version: '3.3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "postgres:/data/postgres"
volumes:
  postgres:
