# Generated by Django 4.2.7 on 2024-03-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_task', '0002_tag_alter_author_born_date_remove_quote_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
